# the data as a list of dictionaries-must be changed to a list of objects
question_data = [{"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "Who was the only god from Greece who did not get a name change in Rome?",
                  "correct_answer": "Apollo",
                  "incorrect_answers": ["Demeter", "Zeus", "Athena"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "This Greek mythological figure is the god/goddess of battle strategy (among other "
                              "things).",
                  "correct_answer": "Athena",
                  "incorrect_answers": ["Ares", "Artemis", "Apollo"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "In Norse mythology, Thor once dressed as a woman.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "Who was the Roman god of fire?",
                  "correct_answer": "Vulcan",
                  "incorrect_answers": ["Apollo", "Jupiter", "Mercury"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "Neptune&#039;s greek name was...",
                  "correct_answer": "Poseidon",
                  "incorrect_answers": ["Ares", "Zeus", "Apollo"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "Which of the following Mesopotamian mythological figures was NOT a deity?",
                  "correct_answer": "Enkidu",
                  "incorrect_answers": ["Enki", "Enlil", "Enkimdu"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "This Greek goddess's name was chosen for the dwarf planet responsible for discord on Pluto's classification amongst astronomers.",
                  "correct_answer": "Eris",
                  "incorrect_answers": ["Charon", "Ceres", "Dysnomia"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "hard",
                  "question": "In Greek Mythology, who was the daughter of King Minos?",
                  "correct_answer": "Ariadne",
                  "incorrect_answers": ["Athena", "Ariel", "Alana"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "In Greek Mythology, who killed Achilles?",
                  "correct_answer": "Paris",
                  "incorrect_answers": ["Hector", "Helen", "Pericles"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "Which figure from Greek mythology traveled to the underworld to return his wife "
                              "Eurydice to the land of the living?",
                  "correct_answer": "Orpheus",
                  "incorrect_answers": ["Hercules", "Perseus", "Daedalus"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "hard",
                  "question": "Which of the following is NOT a god in Norse Mythology.",
                  "correct_answer": "Jens",
                  "incorrect_answers": ["Loki", "Tyr", "Snotra"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "hard",
                  "question": "Nidhogg is a mythical creature from what mythology?",
                  "correct_answer": "Norse",
                  "incorrect_answers": ["Egyptian", "Greek", "Hindu"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "medium",
                  "question": "In Greek mythology, Hera is the goddess of harvest.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "A minotaur is half human half what?",
                  "correct_answer": "Bull",
                  "incorrect_answers": ["Cow", "Horse", "Eagle"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "In most traditions, who was the wife of Zeus?",
                  "correct_answer": "Hera",
                  "incorrect_answers": ["Aphrodite", "Athena", "Hestia"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "What is the name of the Greek god of blacksmiths?",
                  "correct_answer": "Hephaestus",
                  "incorrect_answers": ["Dyntos", "Vulcan", "Artagatus"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "According to the Egyptian Myth of Osiris, who murdered Osiris?",
                  "correct_answer": "Set",
                  "incorrect_answers": ["Horus", "Ra", "Anhur"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "Which of these mythological creatures is said to be half-man and half-horse?",
                  "correct_answer": "Centaur",
                  "incorrect_answers": ["Minotaur", "Pegasus", "Gorgon"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "Which of the following is not one of the Greek Fates?",
                  "correct_answer": "Narcissus",
                  "incorrect_answers": ["Clotho", "Atropos", "Lachesis"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "What mythology did the god &quot;Apollo&quot; come from?",
                  "correct_answer": "Greek and Roman",
                  "incorrect_answers": ["Roman and Spanish", "Greek and Chinese",
                                        "Greek, Roman and Norse"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "easy",
                  "question": "A wyvern is the same as a dragon.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Mythology", "type": "boolean", "difficulty": "hard",
                  "question": "Janus was the Roman god of doorways and passageways.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "easy",
                  "question": "The Nike apparel and footwear brand takes it&#039;s name from the Greek goddess of what?",
                  "correct_answer": "Victory",
                  "incorrect_answers": ["Courage", "Strength", "Honor"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "According to Japanese folklore, what is the favorite food of the Kappa.",
                  "correct_answer": "Cucumbers",
                  "incorrect_answers": ["Kabocha", "Nasu", "Soba"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "hard",
                  "question": "Which Norse God has a horse named Sleipnir?",
                  "correct_answer": "Odin",
                  "incorrect_answers": ["Thor", "Frigg", "Balder"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "The Norse god Odin has two pet crows named &quot;Huginn&quot; and &quot;Muninn&quot;.  "
                              "What do their names mean?",
                  "correct_answer": "Thought &amp; Memory",
                  "incorrect_answers": ["Power &amp; Peace", "War &amp; Learning",
                                        "Sleeping &amp; Waking"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "What is the name of the first human being in Norse mythology?",
                  "correct_answer": "Ask",
                  "incorrect_answers": ["Asmund", "Ake", "Asger"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "What is the name of the Greek god of peaceful deaths?",
                  "correct_answer": "Thanatos",
                  "incorrect_answers": ["Tartarus", "Hades", "Moros"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "Hel was the daughter of which Norse Mythological figure?",
                  "correct_answer": "Loki",
                  "incorrect_answers": ["Thor", "Odin", "Balder"]},
                 {"category": "Mythology", "type": "multiple", "difficulty": "medium",
                  "question": "What animal did Queen Pasipahe sleep with before she gave birth to the Minotaur in "
                              "Greek Mythology?",
                  "correct_answer": "Bull",
                  "incorrect_answers": ["Pig", "Ox", "Horse"]}]
